# Generated by Django 6.0 on 2025-12-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='task name')),
                ('description', models.TextField(blank=True, verbose_name='Task description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed or not')),
            ],
        ),
    ]
